# Update prefix key
unbind C-s
set -g prefix C-s

# Easily reload configuration
bind r source-file ~/.tmux.conf

set -g mouse on

set-option -g status-position top
set-option -g set-titles on
set-option -g set-titles-string "#W"

# Split panes keybindings
bind - split-window -v
bind | split-window -h

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @override_copy_command 'xclip -selection clipboard'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
