[font]
normal = { family = "MesloLGS NF", style = "Regular" }
bold = { family = "MesloLGS NF", style = "Bold" }
italic = { family = "MesloLGS NF", style = "Italic" }
bold_italic = { family = "MesloLGS NF", style = "Bold Italic" }
size = 10

[env]
TERM = 'xterm-256color'

[window]
opacity = 0.95
blur = true
decorations = 'full'
title = 'Alacritty'
dynamic_title = true
padding = { x = 0, y = 0 }
resize_increments = false
