[mgr]
# ratio = [0, 3, 2]
show_hidden = true
linemode = "mtime"

[plugin]
# preloaders = []
# previewers = []

[[plugin.prepend_fetchers]]
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
url   = "*/"
run   = "git"
group = "git"
